<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('diseases')->insert(array(
            0 =>
            array(
                'id' => 1,
                'created_at' => '2022-10-03 07:15:59',
                'updated_at' => '2022-10-03 07:15:59',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Infeksi umum / tidak menular',
                'code' => 'umum',
                'short_description' => 'Infeksi umum / tidak menular',
                'description' => 'Infeksi umum / tidak menular',
                'symptom' => 'Infeksi umum / tidak menular',
                'symptom_details' => NULL,
                'treatment' => 'Infeksi umum / tidak menular',
                'treatment_details' => NULL,
                'priority' => 0,
                'zoonosis' => 0,
            ),
            1 =>
            array(
                'id' => 2,
                'created_at' => '2022-10-03 07:15:59',
                'updated_at' => '2022-10-03 07:15:59',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Penyakit Infeksius Baru',
                'code' => 'pib',
                'short_description' => 'Penyakit Infeksius Baru',
                'description' => 'Penyakit Infeksius Baru',
                'symptom' => 'Penyakit Infeksius Baru',
                'symptom_details' => NULL,
                'treatment' => 'Penyakit Infeksius Baru',
                'treatment_details' => NULL,
                'priority' => 0,
                'zoonosis' => 0,
            ),
            2 =>
            array(
                'id' => 3,
                'created_at' => '2022-10-03 07:16:13',
                'updated_at' => '2022-10-03 07:16:13',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Rabies',
                'code' => 'rabies',
                'short_description' => 'Rabies',
                'description' => 'Rabies',
                'symptom' => 'Rabies',
                'symptom_details' => NULL,
                'treatment' => 'Rabies',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            3 =>
            array(
                'id' => 4,
                'created_at' => '2022-10-03 07:16:28',
                'updated_at' => '2022-10-03 07:16:28',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Anthrax',
                'code' => 'anthrax',
                'short_description' => 'Anthrax',
                'description' => 'Anthrax',
                'symptom' => 'Anthrax',
                'symptom_details' => NULL,
                'treatment' => 'Anthrax',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            4 =>
            array(
                'id' => 5,
                'created_at' => '2022-10-03 07:16:44',
                'updated_at' => '2022-10-03 07:16:44',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'HPAI',
                'code' => 'hpai',
                'short_description' => 'HPAI',
                'description' => 'HPAI',
                'symptom' => 'HPAI',
                'symptom_details' => NULL,
                'treatment' => 'HPAI',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            5 =>
            array(
                'id' => 6,
                'created_at' => '2022-10-03 07:16:44',
                'updated_at' => '2022-10-03 07:16:44',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Leptospirosis',
                'code' => 'leptospirosis',
                'short_description' => 'Leptospirosis',
                'description' => 'Leptospirosis',
                'symptom' => 'Leptospirosis',
                'symptom_details' => NULL,
                'treatment' => 'Leptospirosis',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            6 =>
            array(
                'id' => 7,
                'created_at' => '2022-10-03 07:16:44',
                'updated_at' => '2022-10-03 07:16:44',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Tuberculosis',
                'code' => 'tuberculosis',
                'short_description' => 'Tuberculosis',
                'description' => 'Tuberculosis',
                'symptom' => 'Tuberculosis',
                'symptom_details' => NULL,
                'treatment' => 'Tuberculosis',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            7 =>
            array(
                'id' => 8,
                'created_at' => '2022-10-03 07:16:44',
                'updated_at' => '2022-10-03 07:16:44',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Corona Virus',
                'code' => 'corona',
                'short_description' => 'Corona Virus',
                'description' => 'Corona Virus',
                'symptom' => 'Corona Virus',
                'symptom_details' => NULL,
                'treatment' => 'Corona Virus',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            8 =>
            array(
                'id' => 9,
                'created_at' => '2023-03-16 10:32:30',
                'updated_at' => '2023-03-16 10:32:30',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Flu Burung',
                'code' => 'flu burung',
                'short_description' => 'Flu Bururng',
                'description' => 'Flu Bururng',
                'symptom' => 'Flu Bururng',
                'symptom_details' => NULL,
                'treatment' => 'Flu Bururng',
                'treatment_details' => NULL,
                'priority' => 1,
                'zoonosis' => 1,
            ),
            9 =>
            array(
                'id' => 10,
                'created_at' => '2023-03-16 10:32:30',
                'updated_at' => '2023-03-16 10:32:30',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Malaria',
                'code' => 'malaria',
                'short_description' => 'Malaria',
                'description' => 'Malaria',
                'symptom' => 'Malaria',
                'symptom_details' => NULL,
                'treatment' => 'Malaria',
                'treatment_details' => NULL,
                'priority' => 0,
                'zoonosis' => 0,
            ),
            10 =>
            array(
                'id' => 11,
                'created_at' => '2023-03-16 10:32:30',
                'updated_at' => '2023-03-16 10:32:30',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Meleodosis',
                'code' => 'meleodosis',
                'short_description' => 'Meleodosis',
                'description' => 'Meleodosis',
                'symptom' => 'Meleodosis',
                'symptom_details' => NULL,
                'treatment' => 'Meleodosis',
                'treatment_details' => NULL,
                'priority' => 0,
                'zoonosis' => 0,
            ),
            11 =>
            array(
                'id' => 12,
                'created_at' => '2023-03-16 10:32:30',
                'updated_at' => '2023-03-16 10:32:30',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Nipah',
                'code' => 'nipah',
                'short_description' => 'Nipah',
                'description' => 'Nipah',
                'symptom' => 'Nipah',
                'symptom_details' => NULL,
                'treatment' => 'Nipah',
                'treatment_details' => NULL,
                'priority' => 0,
                'zoonosis' => 0,
            ),
            12 =>
            array(
                'id' => 13,
                'created_at' => '2023-03-16 10:32:30',
                'updated_at' => '2023-03-16 10:32:30',
                'creator' => 2,
                'updater' => 0,
                'status' => 1,
                'name' => 'Brucellosis',
                'code' => 'brucellosis',
                'short_description' => 'Brucellosis',
                'description' => 'Brucellosis',
                'symptom' => 'Brucellosis',
                'symptom_details' => NULL,
                'treatment' => 'Brucellosis',
                'treatment_details' => NULL,
                'priority' => 0,
                'zoonosis' => 0,
            ),
        ));
    }
}
